server.port: 8080

spring:

  application.name: ms-pedido
  zipkin.base-url: http://localhost:9411/
  sleuth.baggage.remote-fields: x-request-id, x-bacon
  #zipkin.enabled: false

  kafka:
    bootstrap-servers: localhost:9092
    group_id: pedidos
    auto-offset-reset: earliest

  data.mongodb:
    uri: mongodb://user:password@localhost:27017/pedido
    database: pedido

topico.pedidos.nome: pedidos
topico.vendas.nome: vendas
topico.vendas_reprovadas.nome: vendas_reprovadas