server.port: 8090

spring:

  application.name: ms-autorizador
  zipkin.base-url: http://localhost:9411/
  sleuth.baggage.remote-fields: x-request-id, x-bacon
  #zipkin.enabled: false

  kafka:
    bootstrap-servers: localhost:9092
    group_id: pedidos
    auto-offset-reset: earliest

  datasource:
    url: jdbc:mysql://localhost:3306/autorizador?createDatabaseIfNotExist=true&useSSL=false
    username: root
  jpa:
    hibernate.ddl-auto: update
    show-sql: true

topico.consumidores.nome: consumidores
topico.comandas.nome: comandas
topico.pedidos.nome: pedidos
topico.vendas.nome: vendas
topico.validacoes.nome: validacoes
topico.vendas_reprovadas.nome: vendas_reprovadas

application.id.config: ms-autorizador